{% set name = "kinparse" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 00c03b174095fce23cec1fed2eeecb56afab27a31ae599b0254901bf206bb5c8

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - kinparse = kinparse.__main__:main

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - future >=0.15.0
    - pyparsing >=2.1.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - kinparse

about:
  home: https://github.com/xesscorp/kinparse
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: This is a parser for KiCad schematic netlist files that are output by EESCHEMA

extra:
  recipe-maintainers:
    - hmaarrfk
